### ISSUE TITLE
No completion inside /* */ comments

### ISSUE THREAD

**Issue by madskristensen** [Peter-Juhasz/HumansTxtLanguageService#1]
I don't get any completion inside /\* */ comments

**Comment by Peter-Juhasz** [comment]
There is one case when you don't get any completion: if you have already used all the well known ones.
Could you please provide an example file and position?

**Comment by Peter-Juhasz** [comment]
And since there is no standard for the human.txt section titles, only the three well-known ones (team, thanks, site - defined in the [example](http://humanstxt.org/humans.txt)), I decided to not to trigger completion by typing characters, only by manual request.

If this is the case, what is your opinion about it?

**Comment by madskristensen** [comment]
Ahh, got it. I wasn't manually requesting Intellisense and Ctrl+J didn't trigger it. If I do, then it works. You may want to add `ShowMemberList` to the completion triggers

**Comment by Peter-Juhasz** [comment]
Thank you for the suggestion. I have added the trigger.

**Comment by madskristensen** [comment]
I think it would be cool if completion showed up while typing and not just when manually invoking it
